// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRl9G0Y2od8P6_GRX4haplfn4_W6o7FuI',
    appId: '1:87900953374:web:4cb50c22883b709e58c70f',
    messagingSenderId: '87900953374',
    projectId: 'gemini-122e9',
    authDomain: 'gemini-122e9.firebaseapp.com',
    storageBucket: 'gemini-122e9.appspot.com',
    measurementId: 'G-FC09QK6T6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqKij_ldMYpTRWapmqeU2HsVcnXiaYJOw',
    appId: '1:87900953374:android:5c12f63baf61de5d58c70f',
    messagingSenderId: '87900953374',
    projectId: 'gemini-122e9',
    storageBucket: 'gemini-122e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVN-lPsWzz08aqmmmGw5LvZk_fPZghQuk',
    appId: '1:87900953374:ios:7c877370143876b658c70f',
    messagingSenderId: '87900953374',
    projectId: 'gemini-122e9',
    storageBucket: 'gemini-122e9.appspot.com',
    iosClientId: '87900953374-lvcc3r9298bsffdi0kdtubedu2r8frpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameraAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVN-lPsWzz08aqmmmGw5LvZk_fPZghQuk',
    appId: '1:87900953374:ios:7c877370143876b658c70f',
    messagingSenderId: '87900953374',
    projectId: 'gemini-122e9',
    storageBucket: 'gemini-122e9.appspot.com',
    iosClientId: '87900953374-lvcc3r9298bsffdi0kdtubedu2r8frpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameraAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRl9G0Y2od8P6_GRX4haplfn4_W6o7FuI',
    appId: '1:87900953374:web:d340f4fc5a42d3aa58c70f',
    messagingSenderId: '87900953374',
    projectId: 'gemini-122e9',
    authDomain: 'gemini-122e9.firebaseapp.com',
    storageBucket: 'gemini-122e9.appspot.com',
    measurementId: 'G-GKCY6ZCVGN',
  );

}